### ISSUE TITLE
ImageEx place holder does not take effect when used in ItemsRepeater date template

### ISSUE THREAD

**Issue by hupo376787** [h82258652/HN.Controls.ImageEx#2]
Hi, I'm using this awsome control, and it's more elegent than Microsoft's ImageEx. But when using HN.Controls.ImageEx in ItemsRepeater's DataTemplate, the PlaceholderTemplate does not take effect.

Here is a small [repo](https://github.com/hupo376787/ImageEx-place-holder-does-not-take-effect-when-used-in-ItemsRepeater-date-template).

So, is there a workaround, thx.

**Comment by hupo376787** [comment]
大佬在吗，这个bug，可以修复吗，谢谢

**Comment by h82258652** [comment]
干，之前忙的时候看到邮件后来就忘了这回事了。
这几天我有空看一下。

**Comment by hupo376787** [comment]
😂😂😂

现在我用回原生的Image了，其他的在XBox上表现都不怎么好，卡卡的

特别是Toolkit出的ImageEx，还存在内存泄漏问题，一直没修复

**Comment by h82258652** [comment]
@hupo376787 卡一般是 IO 阻塞了。toolkit 的一直没处理这个问题，首次加载尤甚。我这个底层是用 System.IO 那套，除了读写的用了异步，其它的 API 我也不晓得会不会阻塞。换 UWP StorageIO 那套应该可以解决，但 WPF 就没法复用了，所以一直没弄。

内存问题不好解决，new 一个 BitmapImage，如果内存不足那就是整个程序爆了，try catch 是抓不足的，我有个壁纸的应用，商店后台一堆 w10m 显示内存不足炸了。目前我这个也是用弱引用来做内存缓存，只能等 GC 来释放，目前想不到好的解决思路。

**Comment by hupo376787** [comment]
我们的app是模仿Netflix首页那样，有很多横向的ListView，用了带PlaceHolder的都是反应比较慢，提issue，他们官方也是互相扯皮推诿，也没人解决。不过大佬的控件比ImageEx好太多了，至少内存方面没啥毛病，我这面测试过。

**Comment by h82258652** [comment]
umm，这边没重现出来。
WinUI 版本 [2.3.200213001](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.3.200213001)

![Snipaste_2020-04-07_11-22-57](https://user-images.githubusercontent.com/5144550/78626817-77602680-78c2-11ea-8b24-4389b4e567df.png)
上图  ItemTemplate 是 resharper bug，实际起作用的。
![Snipaste_2020-04-07_11-23-20](https://user-images.githubusercontent.com/5144550/78626827-7dee9e00-78c2-11ea-83ec-79e93355b333.png)

ItemsRepeater 我没怎么用过，但试了下是需要设置 item 的确定大小，否则滚动条会很奇怪。
另外说一下 Placeholder 是 Source 为 null 时才起作用，空字符串还是会走 Loading 然后 Failed 掉。也许要调整一下这个 API 设计。。。

**Comment by hupo376787** [comment]
我以后有时间试一下，先关了，谢谢
